/**
 * ReportGenerator - Generate PDF reports for measurements
 */

import type { SplReading } from './splMeter';
import type { SpectrumFrame } from '../websocket/protocol';

export interface ReportData {
  title: string;
  timestamp: string;
  measurements: {
    spl?: SplReading;
    spectrum?: SpectrumFrame;
    notes?: string;
  };
  screenshots?: string[];
}

export class ReportGenerator {
  /**
   * Generate a simple HTML report
   */
  static generateHtmlReport(data: ReportData): string {
    const { title, timestamp, measurements, screenshots } = data;

    let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #333;
    }
    h1 { color: #1a1a2a; border-bottom: 2px solid #38d9a9; padding-bottom: 10px; }
    h2 { color: #38d9a9; margin-top: 30px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
    .metric { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
    .metric-label { font-weight: 500; }
    .metric-value { font-family: monospace; color: #38d9a9; }
    .warning { color: #ffc107; }
    .danger { color: #ff6b6b; }
    .safe { color: #38d9a9; }
    .screenshot { max-width: 100%; margin: 20px 0; border: 1px solid #ddd; border-radius: 8px; }
    .notes { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">
    <p>Generated: ${timestamp}</p>
    <p>AudioFlow Spectrum Analyzer Report</p>
  </div>
`;

    // SPL Measurements
    if (measurements.spl) {
      const spl = measurements.spl;
      const levelClass = spl.current > 85 ? 'danger' : spl.current > 70 ? 'warning' : 'safe';

      html += `
  <h2>Sound Pressure Level</h2>
  <div class="metric">
    <span class="metric-label">Current SPL</span>
    <span class="metric-value ${levelClass}">${spl.current.toFixed(1)} dB(A)</span>
  </div>
  <div class="metric">
    <span class="metric-label">Peak SPL</span>
    <span class="metric-value ${spl.peak > 85 ? 'danger' : ''}">${spl.peak.toFixed(1)} dB(A)</span>
  </div>
  <div class="metric">
    <span class="metric-label">Average (Leq)</span>
    <span class="metric-value">${spl.average.toFixed(1)} dB(A)</span>
  </div>
  <div class="metric">
    <span class="metric-label">Minimum</span>
    <span class="metric-value">${spl.min.toFixed(1)} dB(A)</span>
  </div>
  <div class="metric">
    <span class="metric-label">Maximum</span>
    <span class="metric-value">${spl.max.toFixed(1)} dB(A)</span>
  </div>
`;
    }

    // Notes
    if (measurements.notes) {
      html += `
  <h2>Notes</h2>
  <div class="notes">${measurements.notes}</div>
`;
    }

    // Screenshots
    if (screenshots && screenshots.length > 0) {
      html += `
  <h2>Screenshots</h2>
`;
      screenshots.forEach((screenshot, i) => {
        html += `<img class="screenshot" src="${screenshot}" alt="Screenshot ${i + 1}" />`;
      });
    }

    html += `
  <div class="footer">
    <p>Generated by AudioFlow Spectrum Analyzer</p>
    <p>${new Date().toLocaleString()}</p>
  </div>
</body>
</html>
`;

    return html;
  }

  /**
   * Trigger browser print dialog (can save as PDF)
   */
  static printReport(data: ReportData): void {
    const html = this.generateHtmlReport(data);
    const printWindow = window.open('', '_blank');

    if (!printWindow) {
      console.error('Failed to open print window');
      return;
    }

    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content to load then print
    printWindow.onload = () => {
      printWindow.print();
    };
  }

  /**
   * Download report as HTML file
   */
  static downloadReport(data: ReportData): void {
    const html = this.generateHtmlReport(data);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `audioflow-report-${Date.now()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Capture canvas as data URL
   */
  static captureCanvas(canvas: HTMLCanvasElement): string {
    return canvas.toDataURL('image/png');
  }
}
